
  CREATE OR REPLACE EDITIONABLE TRIGGER "DEMO"."HR_DEPARTMENTS_BIU_TRG"
BEFORE INSERT OR UPDATE ON hr_departments FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :new.created_at := NVL(:new.created_at, SYSTIMESTAMP);
        :new.created_by := NVL(:new.created_by, COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER')));
    END IF;
    IF UPDATING THEN
        :new.updated_at := SYSTIMESTAMP;
        :new.updated_by := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    END IF;
END;

/
ALTER TRIGGER "DEMO"."HR_DEPARTMENTS_BIU_TRG" ENABLE;
