-- ====================================================================
-- Script: 02_sync_identity_sequences.sql
-- Description: Synchronize table identity sequences with existing table max IDs
-- ====================================================================

SET DEFINE OFF;

ALTER TABLE hr_leave_types MODIFY (leave_type_id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE));
ALTER TABLE hr_users MODIFY (user_id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE));
ALTER TABLE hr_user_roles MODIFY (user_role_id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE));
ALTER TABLE hr_leave_balances MODIFY (balance_id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE));
ALTER TABLE hr_leave_requests MODIFY (request_id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE));
ALTER TABLE hr_leave_request_events MODIFY (event_id GENERATED BY DEFAULT ON NULL AS IDENTITY (START WITH LIMIT VALUE));
