
  CREATE TABLE "DEMO"."HR_SYSTEM_SETTINGS"
   (	"SETTING_CODE" VARCHAR2(50 CHAR) NOT NULL ENABLE,
	"SETTING_VALUE" VARCHAR2(4000 CHAR) NOT NULL ENABLE,
	"DESCRIPTION" VARCHAR2(1000 CHAR),
	"CREATED_AT" TIMESTAMP (6) WITH LOCAL TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL ENABLE,
	"CREATED_BY" VARCHAR2(100 CHAR) DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER')) NOT NULL ENABLE,
	"UPDATED_AT" TIMESTAMP (6) WITH LOCAL TIME ZONE,
	"UPDATED_BY" VARCHAR2(100 CHAR)
   ) ;
ALTER TABLE "DEMO"."HR_SYSTEM_SETTINGS" ADD CONSTRAINT "PK_HR_SYSTEM_SETTINGS" PRIMARY KEY ("SETTING_CODE")
  USING INDEX  ENABLE;
