-- =============================================================================
-- Script: 01_hr_canonical_schema_and_seed.sql
-- Date:   2026-08-31
-- Target: Oracle Database 19c / APEX 26.1 / DEMO Schema
-- Scope:  Creates all 9 canonical HR tables, constraints, indexes, triggers,
--         column/table comments, and seeds rich demo/test data.
-- =============================================================================

SET DEFINE OFF;
SET TIMING ON;
SET SERVEROUTPUT ON;

PROMPT >>> Checking Session Identity before running DDL...
SELECT sys_context('USERENV', 'SESSION_USER') AS session_user,
       sys_context('USERENV', 'CURRENT_SCHEMA') AS current_schema,
       sys_context('USERENV', 'DB_NAME') AS db_name
  FROM dual;

PROMPT >>> Dropping existing HR objects if present (clean slate)...
BEGIN
    FOR t IN (SELECT table_name FROM user_tables WHERE table_name LIKE 'HR\_%' ESCAPE '\') LOOP
        EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
    END LOOP;
END;
/

-- =============================================================================
-- TABLE CREATION
-- =============================================================================

PROMPT >>> Creating Table 1: HR_ROLES...
CREATE TABLE hr_roles (
    role_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    role_code       VARCHAR2(30 CHAR)               NOT NULL,
    role_name       VARCHAR2(100 CHAR)              NOT NULL,
    description     VARCHAR2(500 CHAR),
    created_at      TIMESTAMP WITH LOCAL TIME ZONE  DEFAULT SYSTIMESTAMP NOT NULL,
    created_by      VARCHAR2(100 CHAR)              DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER')) NOT NULL,
    updated_at      TIMESTAMP WITH LOCAL TIME ZONE,
    updated_by      VARCHAR2(100 CHAR),
    CONSTRAINT pk_hr_roles PRIMARY KEY (role_id),
    CONSTRAINT uq_hr_roles_code UNIQUE (role_code)
);

COMMENT ON TABLE hr_roles IS 'Application security roles defining authorization scopes and privileges across Employee and Admin apps.';
COMMENT ON COLUMN hr_roles.role_id IS 'Primary key surrogate identifier for the role.';
COMMENT ON COLUMN hr_roles.role_code IS 'Unique uppercase machine-readable identifier for the role (e.g. EMPLOYEE, MANAGER, ADMIN, SUPER_ADMIN).';
COMMENT ON COLUMN hr_roles.role_name IS 'Display name for the role shown in user management and administrative UI.';
COMMENT ON COLUMN hr_roles.description IS 'Narrative description explaining the responsibilities and access privileges granted by this role.';
COMMENT ON COLUMN hr_roles.created_at IS 'Timestamp when the role record was created.';
COMMENT ON COLUMN hr_roles.created_by IS 'Username of the user or system session that created the role record.';
COMMENT ON COLUMN hr_roles.updated_at IS 'Timestamp when the role record was last updated.';
COMMENT ON COLUMN hr_roles.updated_by IS 'Username of the user or system session that last updated the role record.';

PROMPT >>> Creating Table 2: HR_DEPARTMENTS...
CREATE TABLE hr_departments (
    department_id   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    department_code VARCHAR2(30 CHAR)               NOT NULL,
    department_name VARCHAR2(100 CHAR)              NOT NULL,
    manager_id      NUMBER,
    active_yn       VARCHAR2(1 CHAR)                DEFAULT 'Y' NOT NULL,
    created_at      TIMESTAMP WITH LOCAL TIME ZONE  DEFAULT SYSTIMESTAMP NOT NULL,
    created_by      VARCHAR2(100 CHAR)              DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER')) NOT NULL,
    updated_at      TIMESTAMP WITH LOCAL TIME ZONE,
    updated_by      VARCHAR2(100 CHAR),
    CONSTRAINT pk_hr_departments PRIMARY KEY (department_id),
    CONSTRAINT uq_hr_departments_code UNIQUE (department_code),
    CONSTRAINT ck_hr_departments_active CHECK (active_yn IN ('Y', 'N'))
);

COMMENT ON TABLE hr_departments IS 'Organizational departments structuring employee teams and reporting lines.';
COMMENT ON COLUMN hr_departments.department_id IS 'Primary key surrogate identifier for the department.';
COMMENT ON COLUMN hr_departments.department_code IS 'Unique uppercase department code (e.g. DEP_ENG, DEP_HR, DEP_FIN, DEP_EXEC).';
COMMENT ON COLUMN hr_departments.department_name IS 'Human-readable name of the department.';
COMMENT ON COLUMN hr_departments.manager_id IS 'Foreign key to HR_USERS referencing the employee who heads the department.';
COMMENT ON COLUMN hr_departments.active_yn IS 'Flag indicating whether the department is active (Y) or archived/inactive (N).';
COMMENT ON COLUMN hr_departments.created_at IS 'Timestamp when the department record was created.';
COMMENT ON COLUMN hr_departments.created_by IS 'Username of the user or system session that created the department.';
COMMENT ON COLUMN hr_departments.updated_at IS 'Timestamp when the department record was last updated.';
COMMENT ON COLUMN hr_departments.updated_by IS 'Username of the user or system session that last updated the department.';

PROMPT >>> Creating Table 3: HR_USERS...
CREATE TABLE hr_users (
    user_id         NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    username        VARCHAR2(100 CHAR)              NOT NULL,
    full_name       VARCHAR2(150 CHAR)              NOT NULL,
    email           VARCHAR2(255 CHAR)              NOT NULL,
    manager_id      NUMBER,
    department_id   NUMBER,
    active_yn       VARCHAR2(1 CHAR)                DEFAULT 'Y' NOT NULL,
    created_at      TIMESTAMP WITH LOCAL TIME ZONE  DEFAULT SYSTIMESTAMP NOT NULL,
    created_by      VARCHAR2(100 CHAR)              DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER')) NOT NULL,
    updated_at      TIMESTAMP WITH LOCAL TIME ZONE,
    updated_by      VARCHAR2(100 CHAR),
    CONSTRAINT pk_hr_users PRIMARY KEY (user_id),
    CONSTRAINT uq_hr_users_username UNIQUE (username),
    CONSTRAINT uq_hr_users_email UNIQUE (email),
    CONSTRAINT ck_hr_users_active CHECK (active_yn IN ('Y', 'N')),
    CONSTRAINT fk_hr_users_manager FOREIGN KEY (manager_id)
        REFERENCES hr_users (user_id),
    CONSTRAINT fk_hr_users_department FOREIGN KEY (department_id)
        REFERENCES hr_departments (department_id)
);

COMMENT ON TABLE hr_users IS 'Employee identities, profiles, manager reporting lines, and system user mappings.';
COMMENT ON COLUMN hr_users.user_id IS 'Primary key surrogate identifier for the user/employee.';
COMMENT ON COLUMN hr_users.username IS 'Unique uppercase application username matching APEX APP_USER session identity.';
COMMENT ON COLUMN hr_users.full_name IS 'Full name of the employee for UI display and reports.';
COMMENT ON COLUMN hr_users.email IS 'Unique organizational email address for notifications and correspondence.';
COMMENT ON COLUMN hr_users.manager_id IS 'Self-referencing foreign key to HR_USERS representing the direct reporting manager.';
COMMENT ON COLUMN hr_users.department_id IS 'Foreign key to HR_DEPARTMENTS indicating organizational department assignment.';
COMMENT ON COLUMN hr_users.active_yn IS 'Flag indicating whether the user account is active (Y) or deactivated (N).';
COMMENT ON COLUMN hr_users.created_at IS 'Timestamp when the user account was created.';
COMMENT ON COLUMN hr_users.created_by IS 'Username of the user or system session that created the account.';
COMMENT ON COLUMN hr_users.updated_at IS 'Timestamp when the user account was last updated.';
COMMENT ON COLUMN hr_users.updated_by IS 'Username of the user or system session that last updated the account.';

ALTER TABLE hr_departments
    ADD CONSTRAINT fk_hr_departments_manager FOREIGN KEY (manager_id)
        REFERENCES hr_users (user_id);

PROMPT >>> Creating Table 4: HR_USER_ROLES...
CREATE TABLE hr_user_roles (
    user_role_id    NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id         NUMBER                          NOT NULL,
    role_id         NUMBER                          NOT NULL,
    created_at      TIMESTAMP WITH LOCAL TIME ZONE  DEFAULT SYSTIMESTAMP NOT NULL,
    created_by      VARCHAR2(100 CHAR)              DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER')) NOT NULL,
    updated_at      TIMESTAMP WITH LOCAL TIME ZONE,
    updated_by      VARCHAR2(100 CHAR),
    CONSTRAINT pk_hr_user_roles PRIMARY KEY (user_role_id),
    CONSTRAINT uq_hr_user_roles UNIQUE (user_id, role_id),
    CONSTRAINT fk_hr_user_roles_user FOREIGN KEY (user_id)
        REFERENCES hr_users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_hr_user_roles_role FOREIGN KEY (role_id)
        REFERENCES hr_roles (role_id) ON DELETE CASCADE
);

COMMENT ON TABLE hr_user_roles IS 'Junction table mapping employees to one or more security authorization roles.';
COMMENT ON COLUMN hr_user_roles.user_role_id IS 'Primary key surrogate identifier for the user-role mapping.';
COMMENT ON COLUMN hr_user_roles.user_id IS 'Foreign key referencing the employee in HR_USERS.';
COMMENT ON COLUMN hr_user_roles.role_id IS 'Foreign key referencing the assigned role in HR_ROLES.';
COMMENT ON COLUMN hr_user_roles.created_at IS 'Timestamp when the role assignment was created.';
COMMENT ON COLUMN hr_user_roles.created_by IS 'Username of the user or system session that granted the role.';
COMMENT ON COLUMN hr_user_roles.updated_at IS 'Timestamp when the role assignment was last updated.';
COMMENT ON COLUMN hr_user_roles.updated_by IS 'Username of the user or system session that last modified the role assignment.';

PROMPT >>> Creating Table 5: HR_LEAVE_TYPES...
CREATE TABLE hr_leave_types (
    leave_type_id       NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    leave_type_code     VARCHAR2(30 CHAR)               NOT NULL,
    leave_type_name     VARCHAR2(100 CHAR)              NOT NULL,
    default_entitlement NUMBER(5, 1)                    DEFAULT 0 NOT NULL,
    requires_balance_yn VARCHAR2(1 CHAR)                DEFAULT 'Y' NOT NULL,
    active_yn           VARCHAR2(1 CHAR)                DEFAULT 'Y' NOT NULL,
    display_order       NUMBER                          DEFAULT 10 NOT NULL,
    created_at          TIMESTAMP WITH LOCAL TIME ZONE  DEFAULT SYSTIMESTAMP NOT NULL,
    created_by          VARCHAR2(100 CHAR)              DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER')) NOT NULL,
    updated_at          TIMESTAMP WITH LOCAL TIME ZONE,
    updated_by          VARCHAR2(100 CHAR),
    CONSTRAINT pk_hr_leave_types PRIMARY KEY (leave_type_id),
    CONSTRAINT uq_hr_leave_types_code UNIQUE (leave_type_code),
    CONSTRAINT ck_hr_leave_types_req_bal CHECK (requires_balance_yn IN ('Y', 'N')),
    CONSTRAINT ck_hr_leave_types_active CHECK (active_yn IN ('Y', 'N'))
);

COMMENT ON TABLE hr_leave_types IS 'Leave type catalog specifying policy rules, default quotas, and balance tracking requirements.';
COMMENT ON COLUMN hr_leave_types.leave_type_id IS 'Primary key surrogate identifier for the leave type.';
COMMENT ON COLUMN hr_leave_types.leave_type_code IS 'Unique uppercase code for the leave category (e.g. ANNUAL, SICK, EMERGENCY, UNPAID).';
COMMENT ON COLUMN hr_leave_types.leave_type_name IS 'Descriptive display name for the leave type.';
COMMENT ON COLUMN hr_leave_types.default_entitlement IS 'Default annual allocation in working days for new employees.';
COMMENT ON COLUMN hr_leave_types.requires_balance_yn IS 'Flag indicating whether this leave type consumes an allocated balance (Y) or is untracked (N).';
COMMENT ON COLUMN hr_leave_types.active_yn IS 'Flag indicating whether the leave type is available for new requests (Y) or deprecated (N).';
COMMENT ON COLUMN hr_leave_types.display_order IS 'Numerical sort order for rendering select lists and report summaries.';
COMMENT ON COLUMN hr_leave_types.created_at IS 'Timestamp when the leave type was defined.';
COMMENT ON COLUMN hr_leave_types.created_by IS 'Username of the user or system session that created the leave type.';
COMMENT ON COLUMN hr_leave_types.updated_at IS 'Timestamp when the leave type was last updated.';
COMMENT ON COLUMN hr_leave_types.updated_by IS 'Username of the user or system session that last modified the leave type.';

PROMPT >>> Creating Table 6: HR_LEAVE_BALANCES...
CREATE TABLE hr_leave_balances (
    balance_id          NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id             NUMBER                          NOT NULL,
    leave_type_id       NUMBER                          NOT NULL,
    balance_year        NUMBER(4, 0)                    NOT NULL,
    entitlement_days    NUMBER(5, 1)                    DEFAULT 0 NOT NULL,
    used_days           NUMBER(5, 1)                    DEFAULT 0 NOT NULL,
    pending_days        NUMBER(5, 1)                    DEFAULT 0 NOT NULL,
    adjustment_days     NUMBER(5, 1)                    DEFAULT 0 NOT NULL,
    available_days      NUMBER(5, 1) GENERATED ALWAYS AS (entitlement_days + adjustment_days - used_days - pending_days) VIRTUAL,
    created_at          TIMESTAMP WITH LOCAL TIME ZONE  DEFAULT SYSTIMESTAMP NOT NULL,
    created_by          VARCHAR2(100 CHAR)              DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER')) NOT NULL,
    updated_at          TIMESTAMP WITH LOCAL TIME ZONE,
    updated_by          VARCHAR2(100 CHAR),
    CONSTRAINT pk_hr_leave_balances PRIMARY KEY (balance_id),
    CONSTRAINT uq_hr_leave_balances_year UNIQUE (user_id, leave_type_id, balance_year),
    CONSTRAINT fk_hr_leave_balances_user FOREIGN KEY (user_id)
        REFERENCES hr_users (user_id) ON DELETE CASCADE,
    CONSTRAINT fk_hr_leave_balances_type FOREIGN KEY (leave_type_id)
        REFERENCES hr_leave_types (leave_type_id)
);

COMMENT ON TABLE hr_leave_balances IS 'Yearly leave quotas and consumption tracking per employee and leave type.';
COMMENT ON COLUMN hr_leave_balances.balance_id IS 'Primary key surrogate identifier for the annual balance record.';
COMMENT ON COLUMN hr_leave_balances.user_id IS 'Foreign key referencing the employee in HR_USERS.';
COMMENT ON COLUMN hr_leave_balances.leave_type_id IS 'Foreign key referencing the leave type in HR_LEAVE_TYPES.';
COMMENT ON COLUMN hr_leave_balances.balance_year IS 'Calendar year (e.g. 2026) for which this balance applies.';
COMMENT ON COLUMN hr_leave_balances.entitlement_days IS 'Annual quota allocated to the employee for the year.';
COMMENT ON COLUMN hr_leave_balances.used_days IS 'Total approved leave days consumed by the employee in the year.';
COMMENT ON COLUMN hr_leave_balances.pending_days IS 'Total days currently reserved by pending/submitted leave requests.';
COMMENT ON COLUMN hr_leave_balances.adjustment_days IS 'Positive or negative administrative adjustments made to the quota.';
COMMENT ON COLUMN hr_leave_balances.available_days IS 'Virtual column computing remaining available days (ENTITLEMENT + ADJUSTMENT - USED - PENDING).';
COMMENT ON COLUMN hr_leave_balances.created_at IS 'Timestamp when the balance allocation was created.';
COMMENT ON COLUMN hr_leave_balances.created_by IS 'Username of the user or system session that created the balance.';
COMMENT ON COLUMN hr_leave_balances.updated_at IS 'Timestamp when the balance allocation was last updated.';
COMMENT ON COLUMN hr_leave_balances.updated_by IS 'Username of the user or system session that last adjusted or updated the balance.';

PROMPT >>> Creating Table 7: HR_LEAVE_REQUESTS...
CREATE TABLE hr_leave_requests (
    request_id      NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    user_id         NUMBER                          NOT NULL,
    leave_type_id   NUMBER                          NOT NULL,
    start_date      DATE                            NOT NULL,
    end_date        DATE                            NOT NULL,
    requested_days  NUMBER(5, 1)                    NOT NULL,
    reason          VARCHAR2(4000 CHAR),
    status          VARCHAR2(30 CHAR)               DEFAULT 'SUBMITTED' NOT NULL,
    ai_summary      VARCHAR2(4000 CHAR),
    workflow_id     NUMBER,
    created_at      TIMESTAMP WITH LOCAL TIME ZONE  DEFAULT SYSTIMESTAMP NOT NULL,
    created_by      VARCHAR2(100 CHAR)              DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER')) NOT NULL,
    updated_at      TIMESTAMP WITH LOCAL TIME ZONE,
    updated_by      VARCHAR2(100 CHAR),
    CONSTRAINT pk_hr_leave_requests PRIMARY KEY (request_id),
    CONSTRAINT ck_hr_leave_requests_dates CHECK (end_date >= start_date),
    CONSTRAINT ck_hr_leave_requests_days CHECK (requested_days > 0),
    CONSTRAINT ck_hr_leave_requests_status CHECK (status IN (
        'DRAFT', 'SUBMITTED', 'PENDING', 'PENDING_MANAGER_APPROVAL',
        'PENDING_HR_APPROVAL', 'APPROVED', 'REJECTED', 'CANCELLED',
        'COMPLETED', 'WORKFLOW_ERROR'
    )),
    CONSTRAINT fk_hr_leave_requests_user FOREIGN KEY (user_id)
        REFERENCES hr_users (user_id),
    CONSTRAINT fk_hr_leave_requests_type FOREIGN KEY (leave_type_id)
        REFERENCES hr_leave_types (leave_type_id)
);

COMMENT ON TABLE hr_leave_requests IS 'Leave requests submitted by employees with dates, approval states, and AI summary.';
COMMENT ON COLUMN hr_leave_requests.request_id IS 'Primary key surrogate identifier for the leave request.';
COMMENT ON COLUMN hr_leave_requests.user_id IS 'Foreign key referencing the requesting employee in HR_USERS.';
COMMENT ON COLUMN hr_leave_requests.leave_type_id IS 'Foreign key referencing the leave category in HR_LEAVE_TYPES.';
COMMENT ON COLUMN hr_leave_requests.start_date IS 'Calendar start date of the requested leave period (inclusive).';
COMMENT ON COLUMN hr_leave_requests.end_date IS 'Calendar end date of the requested leave period (inclusive).';
COMMENT ON COLUMN hr_leave_requests.requested_days IS 'Computed number of working days (Mon-Fri) requested for leave.';
COMMENT ON COLUMN hr_leave_requests.reason IS 'Employee-provided justification or notes explaining the request.';
COMMENT ON COLUMN hr_leave_requests.status IS 'Current lifecycle status (e.g. SUBMITTED, PENDING_MANAGER_APPROVAL, PENDING_HR_APPROVAL, APPROVED, REJECTED, CANCELLED).';
COMMENT ON COLUMN hr_leave_requests.ai_summary IS 'Concise natural language summary generated by AI for approvers.';
COMMENT ON COLUMN hr_leave_requests.workflow_id IS 'Correlation ID linking to the APEX Workflow execution instance.';
COMMENT ON COLUMN hr_leave_requests.created_at IS 'Timestamp when the leave request was initially created.';
COMMENT ON COLUMN hr_leave_requests.created_by IS 'Username of the user or session that submitted the request.';
COMMENT ON COLUMN hr_leave_requests.updated_at IS 'Timestamp when the leave request was last updated.';
COMMENT ON COLUMN hr_leave_requests.updated_by IS 'Username of the user or session that last modified the request.';

PROMPT >>> Creating Table 8: HR_LEAVE_REQUEST_EVENTS...
CREATE TABLE hr_leave_request_events (
    event_id        NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY,
    request_id      NUMBER                          NOT NULL,
    event_type      VARCHAR2(50 CHAR)               NOT NULL,
    from_status     VARCHAR2(30 CHAR),
    to_status       VARCHAR2(30 CHAR),
    actor_username  VARCHAR2(100 CHAR)              NOT NULL,
    comments        VARCHAR2(4000 CHAR),
    event_timestamp TIMESTAMP WITH LOCAL TIME ZONE  DEFAULT SYSTIMESTAMP NOT NULL,
    created_at      TIMESTAMP WITH LOCAL TIME ZONE  DEFAULT SYSTIMESTAMP NOT NULL,
    created_by      VARCHAR2(100 CHAR)              DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER')) NOT NULL,
    updated_at      TIMESTAMP WITH LOCAL TIME ZONE,
    updated_by      VARCHAR2(100 CHAR),
    CONSTRAINT pk_hr_leave_request_events PRIMARY KEY (event_id),
    CONSTRAINT fk_hr_lre_request FOREIGN KEY (request_id)
        REFERENCES hr_leave_requests (request_id) ON DELETE CASCADE
);

COMMENT ON TABLE hr_leave_request_events IS 'Chronological audit trail and timeline events tracking status changes and approver actions.';
COMMENT ON COLUMN hr_leave_request_events.event_id IS 'Primary key surrogate identifier for the timeline event record.';
COMMENT ON COLUMN hr_leave_request_events.request_id IS 'Foreign key referencing the parent leave request in HR_LEAVE_REQUESTS.';
COMMENT ON COLUMN hr_leave_request_events.event_type IS 'Type of event transition (e.g. SUBMITTED, MANAGER_APPROVED, MANAGER_REJECTED, CANCELLED, WORKFLOW_STARTED).';
COMMENT ON COLUMN hr_leave_request_events.from_status IS 'Previous status before this event occurred.';
COMMENT ON COLUMN hr_leave_request_events.to_status IS 'New status resulting from this event.';
COMMENT ON COLUMN hr_leave_request_events.actor_username IS 'Username of the user or system component performing the action.';
COMMENT ON COLUMN hr_leave_request_events.comments IS 'Approver notes, rejection reasons, or cancellation comments.';
COMMENT ON COLUMN hr_leave_request_events.event_timestamp IS 'Timestamp when the event action took place.';
COMMENT ON COLUMN hr_leave_request_events.created_at IS 'Timestamp when the event record was logged.';
COMMENT ON COLUMN hr_leave_request_events.created_by IS 'Username of the user or system session that recorded the event.';
COMMENT ON COLUMN hr_leave_request_events.updated_at IS 'Timestamp when the event record was last updated.';
COMMENT ON COLUMN hr_leave_request_events.updated_by IS 'Username of the user or system session that last modified the event record.';

PROMPT >>> Creating Table 9: HR_SYSTEM_SETTINGS...
CREATE TABLE hr_system_settings (
    setting_code    VARCHAR2(50 CHAR)               NOT NULL,
    setting_value   VARCHAR2(4000 CHAR)             NOT NULL,
    description     VARCHAR2(1000 CHAR),
    created_at      TIMESTAMP WITH LOCAL TIME ZONE  DEFAULT SYSTIMESTAMP NOT NULL,
    created_by      VARCHAR2(100 CHAR)              DEFAULT COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER')) NOT NULL,
    updated_at      TIMESTAMP WITH LOCAL TIME ZONE,
    updated_by      VARCHAR2(100 CHAR),
    CONSTRAINT pk_hr_system_settings PRIMARY KEY (setting_code)
);

COMMENT ON TABLE hr_system_settings IS 'Administrative key-value configuration settings controlling business policies and thresholds.';
COMMENT ON COLUMN hr_system_settings.setting_code IS 'Unique uppercase configuration key (e.g. LONG_LEAVE_THRESHOLD, ALLOW_SELF_APPROVAL, COMPANY_NAME).';
COMMENT ON COLUMN hr_system_settings.setting_value IS 'Configuration value stored as text (e.g. 5, N, Apex Cloud Solutions Ltd).';
COMMENT ON COLUMN hr_system_settings.description IS 'Explanation of the setting purpose, expected format, and system behavior impact.';
COMMENT ON COLUMN hr_system_settings.created_at IS 'Timestamp when the configuration setting was defined.';
COMMENT ON COLUMN hr_system_settings.created_by IS 'Username of the user or session that created the setting.';
COMMENT ON COLUMN hr_system_settings.updated_at IS 'Timestamp when the configuration setting was last updated.';
COMMENT ON COLUMN hr_system_settings.updated_by IS 'Username of the user or session that last updated the setting value.';

-- =============================================================================
-- PERFORMANCE INDEXES (Foreign Keys & Queries)
-- =============================================================================

PROMPT >>> Creating Foreign Key & Lookup Indexes...
CREATE INDEX ix_hr_users_dept        ON hr_users (department_id);
CREATE INDEX ix_hr_users_manager     ON hr_users (manager_id);
CREATE INDEX ix_hr_departments_mgr   ON hr_departments (manager_id);
CREATE INDEX ix_hr_user_roles_user   ON hr_user_roles (user_id);
CREATE INDEX ix_hr_user_roles_role   ON hr_user_roles (role_id);
CREATE INDEX ix_hr_leave_bal_user    ON hr_leave_balances (user_id);
CREATE INDEX ix_hr_leave_bal_type    ON hr_leave_balances (leave_type_id);
CREATE INDEX ix_hr_leave_req_user    ON hr_leave_requests (user_id);
CREATE INDEX ix_hr_leave_req_type    ON hr_leave_requests (leave_type_id);
CREATE INDEX ix_hr_leave_req_status  ON hr_leave_requests (status);
CREATE INDEX ix_hr_lre_request       ON hr_leave_request_events (request_id);

-- =============================================================================
-- AUDIT TRIGGERS (BIU)
-- =============================================================================

PROMPT >>> Creating Automatic Audit Triggers...
CREATE OR REPLACE TRIGGER hr_roles_biu_trg
BEFORE INSERT OR UPDATE ON hr_roles FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :new.created_at := NVL(:new.created_at, SYSTIMESTAMP);
        :new.created_by := NVL(:new.created_by, COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER')));
    END IF;
    IF UPDATING THEN
        :new.updated_at := SYSTIMESTAMP;
        :new.updated_by := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    END IF;
END;
/

CREATE OR REPLACE TRIGGER hr_departments_biu_trg
BEFORE INSERT OR UPDATE ON hr_departments FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :new.created_at := NVL(:new.created_at, SYSTIMESTAMP);
        :new.created_by := NVL(:new.created_by, COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER')));
    END IF;
    IF UPDATING THEN
        :new.updated_at := SYSTIMESTAMP;
        :new.updated_by := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    END IF;
END;
/

CREATE OR REPLACE TRIGGER hr_users_biu_trg
BEFORE INSERT OR UPDATE ON hr_users FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :new.created_at := NVL(:new.created_at, SYSTIMESTAMP);
        :new.created_by := NVL(:new.created_by, COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER')));
    END IF;
    IF UPDATING THEN
        :new.updated_at := SYSTIMESTAMP;
        :new.updated_by := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    END IF;
END;
/

CREATE OR REPLACE TRIGGER hr_user_roles_biu_trg
BEFORE INSERT OR UPDATE ON hr_user_roles FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :new.created_at := NVL(:new.created_at, SYSTIMESTAMP);
        :new.created_by := NVL(:new.created_by, COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER')));
    END IF;
    IF UPDATING THEN
        :new.updated_at := SYSTIMESTAMP;
        :new.updated_by := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    END IF;
END;
/

CREATE OR REPLACE TRIGGER hr_leave_types_biu_trg
BEFORE INSERT OR UPDATE ON hr_leave_types FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :new.created_at := NVL(:new.created_at, SYSTIMESTAMP);
        :new.created_by := NVL(:new.created_by, COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER')));
    END IF;
    IF UPDATING THEN
        :new.updated_at := SYSTIMESTAMP;
        :new.updated_by := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    END IF;
END;
/

CREATE OR REPLACE TRIGGER hr_leave_balances_biu_trg
BEFORE INSERT OR UPDATE ON hr_leave_balances FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :new.created_at := NVL(:new.created_at, SYSTIMESTAMP);
        :new.created_by := NVL(:new.created_by, COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER')));
    END IF;
    IF UPDATING THEN
        :new.updated_at := SYSTIMESTAMP;
        :new.updated_by := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    END IF;
END;
/

CREATE OR REPLACE TRIGGER hr_leave_requests_biu_trg
BEFORE INSERT OR UPDATE ON hr_leave_requests FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :new.created_at := NVL(:new.created_at, SYSTIMESTAMP);
        :new.created_by := NVL(:new.created_by, COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER')));
    END IF;
    IF UPDATING THEN
        :new.updated_at := SYSTIMESTAMP;
        :new.updated_by := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    END IF;
END;
/

CREATE OR REPLACE TRIGGER hr_leave_request_events_biu_trg
BEFORE INSERT OR UPDATE ON hr_leave_request_events FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :new.created_at := NVL(:new.created_at, SYSTIMESTAMP);
        :new.created_by := NVL(:new.created_by, COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER')));
    END IF;
    IF UPDATING THEN
        :new.updated_at := SYSTIMESTAMP;
        :new.updated_by := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    END IF;
END;
/

CREATE OR REPLACE TRIGGER hr_system_settings_biu_trg
BEFORE INSERT OR UPDATE ON hr_system_settings FOR EACH ROW
BEGIN
    IF INSERTING THEN
        :new.created_at := NVL(:new.created_at, SYSTIMESTAMP);
        :new.created_by := NVL(:new.created_by, COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER')));
    END IF;
    IF UPDATING THEN
        :new.updated_at := SYSTIMESTAMP;
        :new.updated_by := COALESCE(SYS_CONTEXT('APEX$SESSION', 'APP_USER'), SYS_CONTEXT('USERENV', 'SESSION_USER'));
    END IF;
END;
/

-- =============================================================================
-- SEED DATA
-- =============================================================================

PROMPT >>> Seeding HR_ROLES...
INSERT INTO hr_roles (role_id, role_code, role_name, description)
VALUES (1, 'EMPLOYEE', 'Employee', 'Employee self-service access to submit and manage own leave');

INSERT INTO hr_roles (role_id, role_code, role_name, description)
VALUES (2, 'MANAGER', 'Manager', 'Direct-report leave approval and team calendar visibility');

INSERT INTO hr_roles (role_id, role_code, role_name, description)
VALUES (3, 'ADMIN', 'HR Administrator', 'HR administration, approval tasks, and leave balance maintenance');

INSERT INTO hr_roles (role_id, role_code, role_name, description)
VALUES (4, 'SUPER_ADMIN', 'Super Administrator', 'Full system configuration, security role assignment, and user administration');

PROMPT >>> Seeding HR_DEPARTMENTS (without manager references first)...
INSERT INTO hr_departments (department_id, department_code, department_name, manager_id, active_yn)
VALUES (10, 'DEP_ENG', 'Engineering & Technology', NULL, 'Y');

INSERT INTO hr_departments (department_id, department_code, department_name, manager_id, active_yn)
VALUES (20, 'DEP_HR', 'Human Resources', NULL, 'Y');

INSERT INTO hr_departments (department_id, department_code, department_name, manager_id, active_yn)
VALUES (30, 'DEP_FIN', 'Finance & Operations', NULL, 'Y');

INSERT INTO hr_departments (department_id, department_code, department_name, manager_id, active_yn)
VALUES (40, 'DEP_EXEC', 'Executive Leadership', NULL, 'Y');

PROMPT >>> Seeding HR_USERS...
-- Top Executive / Admin
INSERT INTO hr_users (user_id, username, full_name, email, manager_id, department_id, active_yn)
VALUES (1, 'ADMIN001', 'Samira Administrator', 'samira.admin@example.com', NULL, 40, 'Y');

-- Manager & HR Admin reporting to Samira
INSERT INTO hr_users (user_id, username, full_name, email, manager_id, department_id, active_yn)
VALUES (2, 'MGR001', 'Mona Manager', 'mona.manager@example.com', 1, 10, 'Y');

INSERT INTO hr_users (user_id, username, full_name, email, manager_id, department_id, active_yn)
VALUES (3, 'HR001', 'Hala HR', 'hala.hr@example.com', 1, 20, 'Y');

-- Employees reporting to Mona Manager
INSERT INTO hr_users (user_id, username, full_name, email, manager_id, department_id, active_yn)
VALUES (4, 'EMP001', 'Ahmed Employee', 'ahmed.employee@example.com', 2, 10, 'Y');

INSERT INTO hr_users (user_id, username, full_name, email, manager_id, department_id, active_yn)
VALUES (5, 'EMP002', 'Elena Engineer', 'elena.engineer@example.com', 2, 10, 'Y');

PROMPT >>> Updating HR_DEPARTMENTS with resolved manager IDs...
UPDATE hr_departments SET manager_id = 2 WHERE department_id = 10;
UPDATE hr_departments SET manager_id = 3 WHERE department_id = 20;
UPDATE hr_departments SET manager_id = 2 WHERE department_id = 30;
UPDATE hr_departments SET manager_id = 1 WHERE department_id = 40;

PROMPT >>> Seeding HR_USER_ROLES...
-- EMP001: EMPLOYEE
INSERT INTO hr_user_roles (user_id, role_id) VALUES (4, 1);

-- EMP002: EMPLOYEE
INSERT INTO hr_user_roles (user_id, role_id) VALUES (5, 1);

-- MGR001: EMPLOYEE, MANAGER, ADMIN
INSERT INTO hr_user_roles (user_id, role_id) VALUES (2, 1);
INSERT INTO hr_user_roles (user_id, role_id) VALUES (2, 2);
INSERT INTO hr_user_roles (user_id, role_id) VALUES (2, 3);

-- HR001: EMPLOYEE, ADMIN
INSERT INTO hr_user_roles (user_id, role_id) VALUES (3, 1);
INSERT INTO hr_user_roles (user_id, role_id) VALUES (3, 3);

-- ADMIN001: EMPLOYEE, ADMIN, SUPER_ADMIN
INSERT INTO hr_user_roles (user_id, role_id) VALUES (1, 1);
INSERT INTO hr_user_roles (user_id, role_id) VALUES (1, 3);
INSERT INTO hr_user_roles (user_id, role_id) VALUES (1, 4);

PROMPT >>> Seeding HR_LEAVE_TYPES...
INSERT INTO hr_leave_types (leave_type_id, leave_type_code, leave_type_name, default_entitlement, requires_balance_yn, active_yn, display_order)
VALUES (1, 'ANNUAL', 'Annual Vacation Leave', 21, 'Y', 'Y', 10);

INSERT INTO hr_leave_types (leave_type_id, leave_type_code, leave_type_name, default_entitlement, requires_balance_yn, active_yn, display_order)
VALUES (2, 'SICK', 'Sick Leave', 15, 'Y', 'Y', 20);

INSERT INTO hr_leave_types (leave_type_id, leave_type_code, leave_type_name, default_entitlement, requires_balance_yn, active_yn, display_order)
VALUES (3, 'EMERGENCY', 'Emergency Leave', 5, 'Y', 'Y', 30);

INSERT INTO hr_leave_types (leave_type_id, leave_type_code, leave_type_name, default_entitlement, requires_balance_yn, active_yn, display_order)
VALUES (4, 'UNPAID', 'Unpaid Leave', 0, 'N', 'Y', 40);

INSERT INTO hr_leave_types (leave_type_id, leave_type_code, leave_type_name, default_entitlement, requires_balance_yn, active_yn, display_order)
VALUES (5, 'MATERNITY', 'Maternity Leave', 60, 'Y', 'Y', 50);

INSERT INTO hr_leave_types (leave_type_id, leave_type_code, leave_type_name, default_entitlement, requires_balance_yn, active_yn, display_order)
VALUES (6, 'PATERNITY', 'Paternity Leave', 10, 'Y', 'Y', 60);

PROMPT >>> Seeding HR_LEAVE_BALANCES (Year 2026)...
-- EMP001 (Ahmed): 21 entitlement, 7 used -> 14 available
INSERT INTO hr_leave_balances (user_id, leave_type_id, balance_year, entitlement_days, used_days, pending_days, adjustment_days)
VALUES (4, 1, 2026, 21, 7, 0, 0);

INSERT INTO hr_leave_balances (user_id, leave_type_id, balance_year, entitlement_days, used_days, pending_days, adjustment_days)
VALUES (4, 2, 2026, 15, 2, 0, 0);

INSERT INTO hr_leave_balances (user_id, leave_type_id, balance_year, entitlement_days, used_days, pending_days, adjustment_days)
VALUES (4, 3, 2026, 5, 0, 0, 0);

-- EMP002 (Elena): 21 entitlement, 5 used, 3 pending -> 13 available
INSERT INTO hr_leave_balances (user_id, leave_type_id, balance_year, entitlement_days, used_days, pending_days, adjustment_days)
VALUES (5, 1, 2026, 21, 5, 3, 0);

INSERT INTO hr_leave_balances (user_id, leave_type_id, balance_year, entitlement_days, used_days, pending_days, adjustment_days)
VALUES (5, 2, 2026, 15, 0, 0, 0);

INSERT INTO hr_leave_balances (user_id, leave_type_id, balance_year, entitlement_days, used_days, pending_days, adjustment_days)
VALUES (5, 3, 2026, 5, 0, 0, 0);

-- MGR001 (Mona): 25 entitlement, 8 used, 2 adjustment -> 19 available
INSERT INTO hr_leave_balances (user_id, leave_type_id, balance_year, entitlement_days, used_days, pending_days, adjustment_days)
VALUES (2, 1, 2026, 25, 8, 0, 2);

INSERT INTO hr_leave_balances (user_id, leave_type_id, balance_year, entitlement_days, used_days, pending_days, adjustment_days)
VALUES (2, 2, 2026, 15, 1, 0, 0);

INSERT INTO hr_leave_balances (user_id, leave_type_id, balance_year, entitlement_days, used_days, pending_days, adjustment_days)
VALUES (2, 3, 2026, 5, 0, 0, 0);

-- HR001 (Hala): 25 entitlement, 6 used -> 19 available
INSERT INTO hr_leave_balances (user_id, leave_type_id, balance_year, entitlement_days, used_days, pending_days, adjustment_days)
VALUES (3, 1, 2026, 25, 6, 0, 0);

INSERT INTO hr_leave_balances (user_id, leave_type_id, balance_year, entitlement_days, used_days, pending_days, adjustment_days)
VALUES (3, 2, 2026, 15, 0, 0, 0);

-- ADMIN001 (Samira): 30 entitlement, 10 used -> 20 available
INSERT INTO hr_leave_balances (user_id, leave_type_id, balance_year, entitlement_days, used_days, pending_days, adjustment_days)
VALUES (1, 1, 2026, 30, 10, 0, 0);

INSERT INTO hr_leave_balances (user_id, leave_type_id, balance_year, entitlement_days, used_days, pending_days, adjustment_days)
VALUES (1, 2, 2026, 15, 0, 0, 0);

PROMPT >>> Seeding HR_LEAVE_REQUESTS & EVENTS...
-- Request 1: EMP001 Approved Annual Leave (7 days)
INSERT INTO hr_leave_requests (request_id, user_id, leave_type_id, start_date, end_date, requested_days, reason, status, ai_summary, workflow_id)
VALUES (101, 4, 1, DATE '2026-03-01', DATE '2026-03-09', 7, 'Family holiday trip to the Mediterranean', 'APPROVED',
        'Ahmed requested 7 days of annual leave for family travel.', 1001);

INSERT INTO hr_leave_request_events (request_id, event_type, from_status, to_status, actor_username, comments, event_timestamp)
VALUES (101, 'SUBMITTED', 'DRAFT', 'SUBMITTED', 'EMP001', 'Submitted for manager approval', TIMESTAMP '2026-02-15 09:00:00');

INSERT INTO hr_leave_request_events (request_id, event_type, from_status, to_status, actor_username, comments, event_timestamp)
VALUES (101, 'MANAGER_APPROVED', 'SUBMITTED', 'APPROVED', 'MGR001', 'Approved, team coverage is confirmed.', TIMESTAMP '2026-02-16 11:30:00');

-- Request 2: EMP001 Approved Sick Leave (2 days)
INSERT INTO hr_leave_requests (request_id, user_id, leave_type_id, start_date, end_date, requested_days, reason, status, ai_summary, workflow_id)
VALUES (102, 4, 2, DATE '2026-05-12', DATE '2026-05-13', 2, 'Severe seasonal flu and fever', 'APPROVED',
        'Ahmed requested 2 days of sick leave for recovery.', 1002);

INSERT INTO hr_leave_request_events (request_id, event_type, from_status, to_status, actor_username, comments, event_timestamp)
VALUES (102, 'SUBMITTED', 'DRAFT', 'SUBMITTED', 'EMP001', 'Medical certificate attached', TIMESTAMP '2026-05-12 08:15:00');

INSERT INTO hr_leave_request_events (request_id, event_type, from_status, to_status, actor_username, comments, event_timestamp)
VALUES (102, 'MANAGER_APPROVED', 'SUBMITTED', 'APPROVED', 'MGR001', 'Approved. Get well soon!', TIMESTAMP '2026-05-12 09:00:00');

-- Request 3: EMP001 Rejected Request (4 days)
INSERT INTO hr_leave_requests (request_id, user_id, leave_type_id, start_date, end_date, requested_days, reason, status, ai_summary, workflow_id)
VALUES (103, 4, 1, DATE '2026-01-15', DATE '2026-01-18', 4, 'Personal time off during sprint close', 'REJECTED',
        'Ahmed requested 4 days of annual leave during key milestone.', 1003);

INSERT INTO hr_leave_request_events (request_id, event_type, from_status, to_status, actor_username, comments, event_timestamp)
VALUES (103, 'SUBMITTED', 'DRAFT', 'SUBMITTED', 'EMP001', 'Request submitted', TIMESTAMP '2026-01-05 14:00:00');

INSERT INTO hr_leave_request_events (request_id, event_type, from_status, to_status, actor_username, comments, event_timestamp)
VALUES (103, 'MANAGER_REJECTED', 'SUBMITTED', 'REJECTED', 'MGR001', 'Critical production release scheduled for that sprint week.', TIMESTAMP '2026-01-06 10:00:00');

-- Request 4: EMP001 Cancelled Request (3 days)
INSERT INTO hr_leave_requests (request_id, user_id, leave_type_id, start_date, end_date, requested_days, reason, status, ai_summary, workflow_id)
VALUES (104, 4, 1, DATE '2026-06-01', DATE '2026-06-03', 3, 'Short personal excursion', 'CANCELLED',
        'Ahmed requested 3 days of leave, later cancelled by employee.', 1004);

INSERT INTO hr_leave_request_events (request_id, event_type, from_status, to_status, actor_username, comments, event_timestamp)
VALUES (104, 'SUBMITTED', 'DRAFT', 'SUBMITTED', 'EMP001', 'Submitted for review', TIMESTAMP '2026-05-20 10:00:00');

INSERT INTO hr_leave_request_events (request_id, event_type, from_status, to_status, actor_username, comments, event_timestamp)
VALUES (104, 'CANCELLED', 'SUBMITTED', 'CANCELLED', 'EMP001', 'Trip postponed due to client workshop.', TIMESTAMP '2026-05-22 16:30:00');

-- Request 5: EMP002 Approved Annual Leave (5 days)
INSERT INTO hr_leave_requests (request_id, user_id, leave_type_id, start_date, end_date, requested_days, reason, status, ai_summary, workflow_id)
VALUES (105, 5, 1, DATE '2026-02-10', DATE '2026-02-14', 5, 'Winter ski vacation in the Alps', 'APPROVED',
        'Elena requested 5 days of annual leave for winter vacation.', 1005);

INSERT INTO hr_leave_request_events (request_id, event_type, from_status, to_status, actor_username, comments, event_timestamp)
VALUES (105, 'SUBMITTED', 'DRAFT', 'SUBMITTED', 'EMP002', 'Submitted request', TIMESTAMP '2026-01-20 11:00:00');

INSERT INTO hr_leave_request_events (request_id, event_type, from_status, to_status, actor_username, comments, event_timestamp)
VALUES (105, 'MANAGER_APPROVED', 'SUBMITTED', 'APPROVED', 'MGR001', 'Approved, enjoy the ski trip!', TIMESTAMP '2026-01-21 09:15:00');

-- Request 6: EMP002 Active Pending Request (3 days)
INSERT INTO hr_leave_requests (request_id, user_id, leave_type_id, start_date, end_date, requested_days, reason, status, ai_summary, workflow_id)
VALUES (106, 5, 1, DATE '2026-10-12', DATE '2026-10-14', 3, 'Attending family wedding in Alexandria', 'PENDING_MANAGER_APPROVAL',
        'Elena requests 3 days of annual leave to attend a family wedding in October.', 2001);

INSERT INTO hr_leave_request_events (request_id, event_type, from_status, to_status, actor_username, comments, event_timestamp)
VALUES (106, 'SUBMITTED', 'DRAFT', 'PENDING_MANAGER_APPROVAL', 'EMP002', 'Submitted for manager approval', TIMESTAMP '2026-08-25 15:20:00');

-- Request 7: MGR001 Approved Annual Leave (8 days)
INSERT INTO hr_leave_requests (request_id, user_id, leave_type_id, start_date, end_date, requested_days, reason, status, ai_summary, workflow_id)
VALUES (107, 2, 1, DATE '2026-04-05', DATE '2026-04-14', 8, 'Spring break and travel', 'APPROVED',
        'Mona requested 8 days of annual leave for spring vacation.', 1007);

INSERT INTO hr_leave_request_events (request_id, event_type, from_status, to_status, actor_username, comments, event_timestamp)
VALUES (107, 'SUBMITTED', 'DRAFT', 'SUBMITTED', 'MGR001', 'Submitted for executive review', TIMESTAMP '2026-03-10 10:00:00');

INSERT INTO hr_leave_request_events (request_id, event_type, from_status, to_status, actor_username, comments, event_timestamp)
VALUES (107, 'MANAGER_APPROVED', 'SUBMITTED', 'APPROVED', 'ADMIN001', 'Approved by Executive Leadership.', TIMESTAMP '2026-03-12 14:00:00');

PROMPT >>> Seeding HR_SYSTEM_SETTINGS...
INSERT INTO hr_system_settings (setting_code, setting_value, description)
VALUES ('LONG_LEAVE_THRESHOLD', '5', 'Threshold in working days above which secondary HR approval is required');

INSERT INTO hr_system_settings (setting_code, setting_value, description)
VALUES ('ALLOW_SELF_APPROVAL', 'N', 'Flag indicating whether managers are allowed to approve their own leave requests');

INSERT INTO hr_system_settings (setting_code, setting_value, description)
VALUES ('MAX_FUTURE_MONTHS', '12', 'Maximum number of months in advance a leave request can be submitted');

INSERT INTO hr_system_settings (setting_code, setting_value, description)
VALUES ('COMPANY_NAME', 'Apex Cloud Solutions Ltd', 'Organization name displayed across self-service and administrative portals');

INSERT INTO hr_system_settings (setting_code, setting_value, description)
VALUES ('FISCAL_YEAR_START_MONTH', '1', 'Calendar month when the annual leave fiscal cycle begins');

INSERT INTO hr_system_settings (setting_code, setting_value, description)
VALUES ('AI_SERVICE_ENABLED', 'Y', 'Master switch enabling conversational AI Assistant and Agent endpoints');

COMMIT;

PROMPT >>> =====================================================================
PROMPT >>> Verification Summary
PROMPT >>> =====================================================================

COLUMN table_name FORMAT A30
COLUMN row_cnt FORMAT 99999

SELECT table_name,
       TO_NUMBER(EXTRACTVALUE(XMLTYPE(DBMS_XMLGEN.GETXML('SELECT COUNT(*) c FROM ' || table_name)), '/ROWSET/ROW/C')) AS row_cnt
  FROM user_tables
 WHERE table_name LIKE 'HR\_%' ESCAPE '\'
 ORDER BY table_name;

PROMPT >>> DDL and seed data generation completed successfully!
