-- Export schema metadata only (never table data). Arguments are supplied by
-- the validated shell/PowerShell wrappers: schema, scope, environment,
-- expected session user, and object-name prefixes.
SET DEFINE ON
DEFINE target_schema = '&1'
DEFINE object_scope = '&2'
DEFINE db_environment = '&3'
DEFINE expected_user = '&4'
DEFINE object_prefixes = '&5'
SET ENCODING UTF-8
SET PAGESIZE 0
-- PAGESIZE 0 alone does not suppress column headings in every SQLcl release,
-- and the driver below is generated by spooling query output. A single stray
-- heading or underline line becomes an unparsable statement in the driver, so
-- turn headings off explicitly as well.
SET HEADING OFF
SET LINESIZE 32767
SET LONG 100000000
SET LONGCHUNKSIZE 100000000
SET TRIMSPOOL ON
SET FEEDBACK OFF
SET ECHO OFF
SET VERIFY OFF
-- SQLcl enables the DDL 'insert' transform by default, which makes
-- DBMS_METADATA append an INSERT /*+ APPEND */ ... KU$ data-movement
-- statement to every table. This mirror is metadata only.
SET DDL INSERT OFF
WHENEVER SQLERROR EXIT SQL.SQLCODE
WHENEVER OSERROR EXIT FAILURE

BEGIN
  IF LOWER('&&object_scope') NOT IN ('tables', 'code') THEN
    RAISE_APPLICATION_ERROR(-20021,
      'Metadata export scope must be tables or code');
  END IF;
END;
/

@@verify_db_access.sql

BEGIN
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'PRETTY', TRUE);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SQLTERMINATOR', TRUE);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'SEGMENT_ATTRIBUTES', FALSE);
  DBMS_METADATA.SET_TRANSFORM_PARAM(DBMS_METADATA.SESSION_TRANSFORM, 'STORAGE', FALSE);
END;
/

-- Object names become filenames and SQL string literals in the generated
-- driver. Reject unexpected names before writing or executing that driver.
DECLARE
  v_count PLS_INTEGER;
BEGIN
  SELECT COUNT(*)
  INTO v_count
  FROM all_objects
  WHERE owner = UPPER('&&target_schema')
    AND (
      (LOWER('&&object_scope') = 'tables' AND object_type = 'TABLE')
      OR
      (LOWER('&&object_scope') = 'code' AND object_type IN (
        'VIEW', 'PACKAGE', 'PACKAGE BODY', 'PROCEDURE', 'FUNCTION', 'TRIGGER'
      ))
    )
    AND (
      '&&object_prefixes' = '*'
      OR EXISTS (
        SELECT 1
        FROM (
          SELECT REGEXP_SUBSTR('&&object_prefixes', '[^,]+', 1, LEVEL) object_prefix
          FROM dual
          CONNECT BY LEVEL <= REGEXP_COUNT('&&object_prefixes', ',') + 1
        ) configured_prefixes
        WHERE INSTR(all_objects.object_name, configured_prefixes.object_prefix) = 1
      )
    )
    AND NOT REGEXP_LIKE(object_name, '^[A-Za-z0-9_$#]+$');

  IF v_count > 0 THEN
    RAISE_APPLICATION_ERROR(-20020,
      'Schema contains object names that are unsafe for metadata export filenames');
  END IF;
END;
/

-- SQLcl cannot SPOOL to a file whose name contains '$' (SP2-0332), and the
-- failure does not stop the script, so such an object would silently vanish
-- from the mirror. Encode '$' as '-S-' in the *filename* only; '-' cannot
-- appear in an Oracle identifier, so the encoding cannot collide. The object
-- name inside the generated DDL is untouched.
--
-- The generated driver statements end in a semicolon, but that semicolon is
-- built with CHR(59) rather than written as a literal ';' inside the string.
-- SQLcl's client-side statement splitter looks for ';' before it knows the
-- character sits inside a quoted literal, so a literal one truncates these
-- SELECTs: SQLcl then returns no rows, prints no error, and exits 0, leaving
-- an empty driver and an empty mirror. Keep CHR(59).
SPOOL scripts/_backup_db_driver_&&object_scope..sql

SELECT 'SPOOL database/&&target_schema/tables/' || REPLACE(table_name, '$', '-S-') || '.sql'
       || CHR(10) || 'SELECT DBMS_METADATA.GET_DDL(''TABLE'', ''' || table_name
       || ''', ''&&target_schema'') FROM DUAL' || CHR(59)
       || CHR(10) || 'SPOOL OFF'
FROM all_tables tables_to_export
WHERE LOWER('&&object_scope') = 'tables'
  AND tables_to_export.owner = UPPER('&&target_schema')
  AND (
    '&&object_prefixes' = '*'
    OR EXISTS (
      SELECT 1
      FROM (
        SELECT REGEXP_SUBSTR('&&object_prefixes', '[^,]+', 1, LEVEL) object_prefix
        FROM dual
        CONNECT BY LEVEL <= REGEXP_COUNT('&&object_prefixes', ',') + 1
      ) configured_prefixes
      WHERE INSTR(tables_to_export.table_name, configured_prefixes.object_prefix) = 1
    )
  )
ORDER BY table_name;

SELECT 'SPOOL database/&&target_schema/views/' || REPLACE(view_name, '$', '-S-') || '.sql'
       || CHR(10) || 'SELECT DBMS_METADATA.GET_DDL(''VIEW'', ''' || view_name
       || ''', ''&&target_schema'') FROM DUAL' || CHR(59)
       || CHR(10) || 'SPOOL OFF'
FROM all_views views_to_export
WHERE LOWER('&&object_scope') = 'code'
  AND views_to_export.owner = UPPER('&&target_schema')
  AND (
    '&&object_prefixes' = '*'
    OR EXISTS (
      SELECT 1
      FROM (
        SELECT REGEXP_SUBSTR('&&object_prefixes', '[^,]+', 1, LEVEL) object_prefix
        FROM dual
        CONNECT BY LEVEL <= REGEXP_COUNT('&&object_prefixes', ',') + 1
      ) configured_prefixes
      WHERE INSTR(views_to_export.view_name, configured_prefixes.object_prefix) = 1
    )
  )
ORDER BY view_name;

SELECT 'SPOOL database/&&target_schema/packages/' || REPLACE(object_name, '$', '-S-') || '_SPEC.sql'
       || CHR(10) || 'SELECT DBMS_METADATA.GET_DDL(''PACKAGE_SPEC'', ''' || object_name
       || ''', ''&&target_schema'') FROM DUAL' || CHR(59)
       || CHR(10) || 'SPOOL OFF'
FROM all_objects objects_to_export
WHERE LOWER('&&object_scope') = 'code'
  AND objects_to_export.owner = UPPER('&&target_schema')
  AND objects_to_export.object_type = 'PACKAGE'
  AND (
    '&&object_prefixes' = '*'
    OR EXISTS (
      SELECT 1
      FROM (
        SELECT REGEXP_SUBSTR('&&object_prefixes', '[^,]+', 1, LEVEL) object_prefix
        FROM dual
        CONNECT BY LEVEL <= REGEXP_COUNT('&&object_prefixes', ',') + 1
      ) configured_prefixes
      WHERE INSTR(objects_to_export.object_name, configured_prefixes.object_prefix) = 1
    )
  )
ORDER BY object_name;

SELECT 'SPOOL database/&&target_schema/packages/' || REPLACE(object_name, '$', '-S-') || '_BODY.sql'
       || CHR(10) || 'SELECT DBMS_METADATA.GET_DDL(''PACKAGE_BODY'', ''' || object_name
       || ''', ''&&target_schema'') FROM DUAL' || CHR(59)
       || CHR(10) || 'SPOOL OFF'
FROM all_objects objects_to_export
WHERE LOWER('&&object_scope') = 'code'
  AND objects_to_export.owner = UPPER('&&target_schema')
  AND objects_to_export.object_type = 'PACKAGE BODY'
  AND (
    '&&object_prefixes' = '*'
    OR EXISTS (
      SELECT 1
      FROM (
        SELECT REGEXP_SUBSTR('&&object_prefixes', '[^,]+', 1, LEVEL) object_prefix
        FROM dual
        CONNECT BY LEVEL <= REGEXP_COUNT('&&object_prefixes', ',') + 1
      ) configured_prefixes
      WHERE INSTR(objects_to_export.object_name, configured_prefixes.object_prefix) = 1
    )
  )
ORDER BY object_name;

SELECT 'SPOOL database/&&target_schema/procedures/' || REPLACE(object_name, '$', '-S-') || '.sql'
       || CHR(10) || 'SELECT DBMS_METADATA.GET_DDL(''PROCEDURE'', ''' || object_name
       || ''', ''&&target_schema'') FROM DUAL' || CHR(59)
       || CHR(10) || 'SPOOL OFF'
FROM all_objects objects_to_export
WHERE LOWER('&&object_scope') = 'code'
  AND objects_to_export.owner = UPPER('&&target_schema')
  AND objects_to_export.object_type = 'PROCEDURE'
  AND (
    '&&object_prefixes' = '*'
    OR EXISTS (
      SELECT 1
      FROM (
        SELECT REGEXP_SUBSTR('&&object_prefixes', '[^,]+', 1, LEVEL) object_prefix
        FROM dual
        CONNECT BY LEVEL <= REGEXP_COUNT('&&object_prefixes', ',') + 1
      ) configured_prefixes
      WHERE INSTR(objects_to_export.object_name, configured_prefixes.object_prefix) = 1
    )
  )
ORDER BY object_name;

SELECT 'SPOOL database/&&target_schema/functions/' || REPLACE(object_name, '$', '-S-') || '.sql'
       || CHR(10) || 'SELECT DBMS_METADATA.GET_DDL(''FUNCTION'', ''' || object_name
       || ''', ''&&target_schema'') FROM DUAL' || CHR(59)
       || CHR(10) || 'SPOOL OFF'
FROM all_objects objects_to_export
WHERE LOWER('&&object_scope') = 'code'
  AND objects_to_export.owner = UPPER('&&target_schema')
  AND objects_to_export.object_type = 'FUNCTION'
  AND (
    '&&object_prefixes' = '*'
    OR EXISTS (
      SELECT 1
      FROM (
        SELECT REGEXP_SUBSTR('&&object_prefixes', '[^,]+', 1, LEVEL) object_prefix
        FROM dual
        CONNECT BY LEVEL <= REGEXP_COUNT('&&object_prefixes', ',') + 1
      ) configured_prefixes
      WHERE INSTR(objects_to_export.object_name, configured_prefixes.object_prefix) = 1
    )
  )
ORDER BY object_name;

SELECT 'SPOOL database/&&target_schema/triggers/' || REPLACE(object_name, '$', '-S-') || '.sql'
       || CHR(10) || 'SELECT DBMS_METADATA.GET_DDL(''TRIGGER'', ''' || object_name
       || ''', ''&&target_schema'') FROM DUAL' || CHR(59)
       || CHR(10) || 'SPOOL OFF'
FROM all_objects objects_to_export
WHERE LOWER('&&object_scope') = 'code'
  AND objects_to_export.owner = UPPER('&&target_schema')
  AND objects_to_export.object_type = 'TRIGGER'
  AND (
    '&&object_prefixes' = '*'
    OR EXISTS (
      SELECT 1
      FROM (
        SELECT REGEXP_SUBSTR('&&object_prefixes', '[^,]+', 1, LEVEL) object_prefix
        FROM dual
        CONNECT BY LEVEL <= REGEXP_COUNT('&&object_prefixes', ',') + 1
      ) configured_prefixes
      WHERE INSTR(objects_to_export.object_name, configured_prefixes.object_prefix) = 1
    )
  )
ORDER BY object_name;

SPOOL OFF

@scripts/_backup_db_driver_&&object_scope..sql

COLUMN manifest_file NEW_VALUE manifest_file NOPRINT
SELECT CASE LOWER('&&object_scope')
         WHEN 'tables' THEN 'manifest-tables.txt'
         WHEN 'code' THEN 'manifest-code.txt'
       END AS manifest_file
FROM dual;

SPOOL database/&&target_schema/&&manifest_file
WITH expected_types (object_type, object_scope) AS (
  SELECT 'TABLE', 'tables' FROM dual UNION ALL
  SELECT 'VIEW', 'code' FROM dual UNION ALL
  SELECT 'PACKAGE', 'code' FROM dual UNION ALL
  SELECT 'PACKAGE BODY', 'code' FROM dual UNION ALL
  SELECT 'PROCEDURE', 'code' FROM dual UNION ALL
  SELECT 'FUNCTION', 'code' FROM dual UNION ALL
  SELECT 'TRIGGER', 'code' FROM dual
)
SELECT expected_types.object_type || '=' || COUNT(all_objects.object_name)
FROM expected_types
LEFT JOIN all_objects
 ON all_objects.owner = UPPER('&&target_schema')
 AND all_objects.object_type = expected_types.object_type
 AND (
   '&&object_prefixes' = '*'
   OR EXISTS (
     SELECT 1
     FROM (
       SELECT REGEXP_SUBSTR('&&object_prefixes', '[^,]+', 1, LEVEL) object_prefix
       FROM dual
       CONNECT BY LEVEL <= REGEXP_COUNT('&&object_prefixes', ',') + 1
     ) configured_prefixes
     WHERE INSTR(all_objects.object_name, configured_prefixes.object_prefix) = 1
   )
 )
WHERE expected_types.object_scope = LOWER('&&object_scope')
GROUP BY expected_types.object_type
ORDER BY expected_types.object_type;
SPOOL OFF

SET DEFINE OFF
EXIT
